# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'DiocamAzureRmPipeline-conn'
    subscriptionId: '7e63ef46-0ec9-4b6d-aa79-1e8fa12568b2'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'FunctionAppsPipelines'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateWebApp/mainDeployFunction.json'
    deploymentMode: 'Incremental'
    deploymentName: 'didiocam'